language: ruby
rvm: 2.2
sudo: required
dist: trusty
env:
  global:
  - secure: Kc5j0fwV/6zHeENXidold1kRCHN7BKVY88Oe+0nNaqlJeaHfm+TUDTrhNghtYk2cEf1hM3SqgUozJvqGGWv+VkmMewv3UBWn0q21qLpyn8NgscnYAATrR4mEZMzq0ZWA63l/6t2l8v8wK7Y15PnbK990u5BLpLyTSqubfLXcx8k=
cache:
  apt: true
before_install:
- curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
- sudo apt-get install -y nodejs build-essential
install:
- npm install --ignore-scripts
script:
- npm run build
after_script:
- npm test
deploy:
- provider: script
  skip_cleanup: true
  script: npm publish dist/pact-mock-service-darwin --access public
  on:
    branch: master
    tags: true
- provider: script
  skip_cleanup: true
  script: npm publish dist/pact-mock-service-linux-ia32 --access public
  on:
    branch: master
    tags: true
- provider: script
  skip_cleanup: true
  script: npm publish dist/pact-mock-service-linux-x64 --access public
  on:
    branch: master
    tags: true
- provider: script
  skip_cleanup: true
  script: npm publish dist/pact-mock-service-win32 --access public
  on:
    branch: master
    tags: true
- provider: script
  skip_cleanup: true
  script: npm publish . --access public
  on:
    branch: master
    tags: true
after_failure:
- find . -iname '*.log' -print0 | xargs -0 cat
